= Thevenin's/Norton's theory (cont.)

== Case 3 (Circuit with dependent source only)

Since the dependaent source depends on a independent source, $E_("TH") = 0$

=== Examples

1. Find Thevinin's equivalent between the terminals a-b.

$ E_("TH") = 0 $

By connecting a current/voltage (1A/1V) supply between the two terminals a and b:

1. Calculate $V_("ab")$ across the 1A current source.
$ therefore R_("ab") = (V_("ab"))/(1A) = R_("TH") $
2. Using mesh analysis:
$ i_1 = -3i_x arrow.r 1 $
$ 0 = i_2(2 + 6 + 8) - i_2(2) - i_3(8) arrow.r 2 $
$ i_3 = -1A arrow.r 3 $
$ i_x = i_2 - i_3 arrow.r 4 $
$ therefore V_("ab") = 8i_x = R_("TH") $

= The theory of the maximum power transfer

If a circuit containing either an independant source and a dependanent source or an independant source soley, is connected to a variable resistance between two terminals a-b, The value of the power ($P_L$) starts from 0 and ends at 0. If the circuit is substituted by a thevinin circuit, $P_L$ can be considered a function with the variable $R_L$. Therefore, to find the maximum power generated by the circuit, the function can be diffrentiated and made equal to 0.

$ I_L = (E_("TH"))/(R_("TH") + R_L) $
$ P_L = (I_L)^2 times R_L $
$ P_L = ((E_("TH"))^2 times R_L) / (R_("TH") = R_L)^2 $
To find the maximum power:
$ (d P_L)/(d R_L) = 0 $
After diffrentiation:
$ R_L = R_("TH") $
$ therefore P_("max") = ((E_("TH"))^2 times R_("TH"))/(4 (R_("TH"))^2) = ((E_("TH"))^2)/(4R_("TH")) W $

=== Examples

1. Find the maximum power.

By disconnecting all power sources:
$ R_("TH") = 9 ohm $

$ E_("TH") = V_("ab") $

Using nodal analysis at $V_1$ :
$ 2 = (V_1 - 0)/12 + (V_1 - 12)/6 $
(3 $ohm$ resistance is ignored since it is connected in series with a current source)

By applying KVL on the first two loops from the right:
$ -V_1 - 6 - 0 + V_("ab") = 0 $
$ E_("TH") = V_("ab") $

$ therefore P_L = ((E_("TH"))^2)/(4R_("TH")) $
