
* The elements of argument

** Claim

- Arguments against plastic surgery are invalid.

** Reasons

1. The misconception of not being safe.

2. The reasons behind getting plastic surgery are not shallow.

3. The money spent on plastic surgery can be a better investment than money spent on other things.

** Evidence

1. Any medical procedure can be risky no matter how big or small if not being done by certified individuals with the experience and technology required.

2. The reasons for surgery do not include being done for someone else as most individuals are pleased to make changes that help overcome insecurities.

3. In addition to plastic surgery being more affordable than before, people spend a lot of money on things they don't need or can't afford like clothes and vehicles.

** Sources

- Sources available to back up statistics.

* "Final" Elements of Argument

The author claims that arguments against plastic surgery are invalid for a number of reasons. First of all, the misconception around the surgery's saftey, the author states that any medical procedure in general, no matter how big or small it is, has its own risks, furthermore adding that simply falling out of bed can be fatal. Second of all, the reasons behind surgery; the author asserts that the reasons behind getting plastic surgery are not as shallow as widely interpreted since people do not get surgery for someone, but rather for themselves as a way to get past their insecurities or past obstacles and better accept themselves. Lastly, the author writes about how plastic surgery is not a waste of money as he compares plastic surgery to other investments like clothes and vehicles, and claims that those objects that are only luxuries are no better investments than plastic surgery. However, the author's claim was weak since he failed to provide enough sources to back it up since only one source was given which did not support any of his reasons or evidence.

* Reason 1 Counter Argument (The misconseptions around its saftey (Plastic surgery is safe))

As true as the author's claim could be to a certain extent, there is evidence that supports the opposite. According to an article from [[clevelandclinic.org]], some complications can occur after surgery or even during it, these complications can include and not only limited to: blood loss, infections, nerve damage and abnormal scarring. These complications would make the recovery process slower in addition to a more painful time recovering. Moreover, according to another article on [[theaestheticsociety.org]], more complications like excessive bruising, numbness and blood clots, that can be life threatening, are likely to happen after most plastic surgeries. With all the previous considered, plastic surgeries are not as safe as claimed by the author.

* Reason 2 Counter Argument (The reasons behind getting plastic surgery are not shallow)

What's more, theaestheticsociety.org reported a 14% increase in aesthetic procedures in 2022, which are only to change one's look and considered shallow. Approximately 55% of those procedures where done in the first half of the year.
