date: 20-2-23

* Lecture #1

** Basic circuit laws (cont.)

Example on Ohm's law:

  A voltage supply of 100V supplies 500W to 4 elements, 10, 12 and 2 in ohm.
  Find the power absorbed by the 4th element.

  $$ I_t = \frac{P}{V} = 5A $$
  $$ P_1 = 5^2 \times 10 = 250W $$
  $$ P_2 = 3^2 \times 12 = 108W $$
  $$ P_3 = 2^2 \times 2 = 8W $$
  $$ \therefore P_4 = P - (P_1 + P_2 + P_3) = 500 - 366 = 134W $$

*** Kirchhoff's Law

**** 1. KVL (Kirchhoff's voltage law)

  In any loop inside a circuit, The sum of voltage across the loop equals zero.

  $$ \Sigma V_{loop} = 0 $$

- Series connection

  Elements are in series connection only if the same current passes through all of them. Therefore the equivelant resistance of n resistors in series equals:

    $$ R_{eq} = \Sigma_{n = 1} R_n $$

- Voltage division

  $$ V = V_t \times \frac{R_1}{R_t} $$

  - When in a series connection, The value of the voltage is directly proportional with the value of the resistance

**** 2. KCL (Kirchhoff's current law)

- Junction

  A junction is a connection point in the circuit between only two elements and the current passing through is constant.

- Node:

  A node is a connection point in the circuit that connects at least three branches and is where the current is branched.

KCL states that the sum of currents going into a node equals the sum of currents going out of the same node

$$ \Sigma I_{in} = \Sigma I_{out} $$

- Parallel connection

  Parallel connection is where elements share the same start and end point and therefore share the same voltage

  $$ \frac{1}{R_{eq}} = \Sigma_{n = 1} \frac{1}{R_n} $$

  - In the case of only two resistors:

    $$ R_{eq} = \frac{R_1 \times R_2}{R_1 + R_2} $$

- Current division

  $$\frac{I_1}{I_2} = \frac{R_2}{R_1}$$

  $$ I_1 = I_t \times \frac{R_2}{R_1 + R_2} $$

  - When in parallel connection, the value of the current is inversly proportional with the value of the resistance.

*** Conductance ($G$)

$$ G = \frac{1}{R} = \omega = S $$
